/**
 * Hook para gerenciar workspace pessoal
 */

import { useState, useEffect, useContext } from 'react';
import { api } from '../services/api';
import { CompanyContext } from '../contexts/CompanyContextDefinition';

interface Column {
  id: string;
  name: string;
  color?: string;
  order: number;
}

interface Task {
  id: string;
  title: string;
  description?: string;
  columnId: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  dueDate?: string;
  isCompleted: boolean;
  metadata?: {
    autoGenerated?: boolean;
    matchId?: string;
    matchScore?: number;
    clientId?: string;
    propertyId?: string;
  };
}

interface Project {
  id: string;
  name: string;
  description?: string;
  isPrivate: boolean;
}

export function usePersonalProject() {
  const { selectedCompany } = useContext(CompanyContext) || {
    selectedCompany: null,
  };
  const [project, setProject] = useState<Project | null>(null);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [columns, setColumns] = useState<Column[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        setError(null);

        // Buscar projeto pessoal
        const projectResponse = await api.get('/kanban/projects/personal/me');
        setProject(projectResponse.data);

        if (projectResponse.data?.id) {
          // Buscar tasks do projeto
          const tasksResponse = await api.get('/kanban/tasks', {
            params: { projectId: projectResponse.data.id },
          });
          setTasks(tasksResponse.data.data || []);

          // Buscar colunas (se disponível)
          try {
            const columnsResponse = await api.get(
              `/kanban/columns/${projectResponse.data.teamId || projectResponse.data.id}`
            );
            setColumns(columnsResponse.data || []);
          } catch {
            // Se não tiver colunas, usar padrão
            setColumns([
              { id: 'todo', name: 'A Fazer', color: '#3B82F6', order: 1 },
              {
                id: 'in_progress',
                name: 'Em Progresso',
                color: '#F59E0B',
                order: 2,
              },
              { id: 'done', name: 'Concluído', color: '#10B981', order: 3 },
            ]);
          }
        }
      } catch (err) {
        const error = err as Error;
        console.error('Erro ao carregar workspace:', error);
        setError(error);
      } finally {
        setLoading(false);
      }
    }

    load();
  }, [selectedCompany?.id]);

  // Calcular estatísticas
  const stats = {
    totalTasks: tasks.length,
    completedTasks: tasks.filter(t => t.isCompleted).length,
    pendingTasks: tasks.filter(t => !t.isCompleted).length,
    matchTasks: tasks.filter(t => t.metadata?.autoGenerated).length,
  };

  // Organizar tasks por coluna
  const tasksByColumn: Record<string, Task[]> = {};
  columns.forEach(col => {
    tasksByColumn[col.id] = tasks.filter(t => t.columnId === col.id);
  });

  return {
    project,
    tasks,
    columns,
    loading,
    error,
    stats,
    tasksByColumn,
  };
}
