/**
 * Tipos para Workspace Pessoal
 */

export interface PersonalProject {
  id: string;
  name: string; // "🎯 Meu Workspace"
  description: string;
  isPersonal: boolean; // SEMPRE true
  status: 'active' | 'completed' | 'archived' | 'cancelled';
  color: string; // "#3B82F6"
  teamId: string;
  createdById: string;
  taskCount: number;
  completedTaskCount: number;
  createdAt: string;
  updatedAt?: string;
}

export interface KanbanColumn {
  id: string;
  name: string;
  position: number;
  projectId: string;
  color?: string;
  createdAt: string;
}

export interface KanbanTask {
  id: string;
  title: string;
  description?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  isCompleted: boolean;
  columnId: string;
  projectId: string;
  assignedToId?: string;
  createdById: string;
  position: number;
  dueDate?: string;
  tags?: string[];
  createdAt: string;
  updatedAt?: string;

  // Metadata para tasks de match
  metadata?: {
    matchId?: string;
    clientId?: string;
    propertyId?: string;
    matchScore?: number;
    autoGenerated?: boolean;
  };
}

export interface PersonalWorkspaceStats {
  totalTasks: number;
  completedTasks: number;
  pendingTasks: number;
  highPriorityTasks: number;
  matchesAccepted: number;
}
