/**
 * Página do Workspace Pessoal
 * Projeto privado com tasks e matches aceitos
 */

import React from 'react';
import styled from 'styled-components';
import { usePersonalProject } from '../hooks/usePersonalProject';
import { useNavigate } from 'react-router-dom';

function MyWorkspacePage() {
  const navigate = useNavigate();
  const { project, tasks, columns, loading, stats, tasksByColumn } =
    usePersonalProject();

  if (loading) {
    return (
      <LoadingContainer>
        <LoadingSpinner />
        <LoadingText>Carregando workspace...</LoadingText>
      </LoadingContainer>
    );
  }

  if (!project) {
    return (
      <ErrorContainer>
        <ErrorIcon>⚠️</ErrorIcon>
        <ErrorTitle>Workspace não encontrado</ErrorTitle>
        <ErrorText>
          Não foi possível carregar seu workspace pessoal. Por favor, tente
          novamente.
        </ErrorText>
      </ErrorContainer>
    );
  }

  return (
    <Container>
      {/* Header */}
      <Header>
        <HeaderContent>
          <TitleSection>
            <Title>
              🏠 Meu Workspace
              <PrivateBadge>Privado</PrivateBadge>
            </Title>
            <Subtitle>Suas tarefas pessoais e matches aceitos</Subtitle>
          </TitleSection>

          <HeaderActions>
            <ViewMatchesButton onClick={() => navigate('/matches')}>
              🎯 Ver Matches
            </ViewMatchesButton>
          </HeaderActions>
        </HeaderContent>
      </Header>

      {/* Estatísticas Rápidas */}
      <StatsSection>
        <StatCard $color='#3B82F6'>
          <StatIcon>📋</StatIcon>
          <StatValue>{stats.totalTasks}</StatValue>
          <StatLabel>Total de Tasks</StatLabel>
        </StatCard>

        <StatCard $color='#10B981'>
          <StatIcon>✅</StatIcon>
          <StatValue>{stats.completedTasks}</StatValue>
          <StatLabel>Concluídas</StatLabel>
        </StatCard>

        <StatCard $color='#F59E0B'>
          <StatIcon>⏳</StatIcon>
          <StatValue>{stats.pendingTasks}</StatValue>
          <StatLabel>Pendentes</StatLabel>
        </StatCard>

        <StatCard $color='#8B5CF6'>
          <StatIcon>🏠</StatIcon>
          <StatValue>{stats.matchTasks}</StatValue>
          <StatLabel>Matches Aceitos</StatLabel>
        </StatCard>
      </StatsSection>

      {/* Quadro Kanban */}
      <KanbanContainer>
        {columns.length === 0 ? (
          <EmptyState>
            <EmptyIcon>📋</EmptyIcon>
            <EmptyTitle>Nenhuma coluna encontrada</EmptyTitle>
            <EmptyText>
              Seu workspace ainda não possui colunas configuradas.
            </EmptyText>
          </EmptyState>
        ) : (
          <KanbanBoard>
            {columns.map(column => {
              const columnTasks = tasksByColumn[column.id] || [];
              return (
                <Column key={column.id}>
                  <ColumnHeader $color={column.color}>
                    <ColumnTitle>{column.name}</ColumnTitle>
                    <TaskCount>{columnTasks.length}</TaskCount>
                  </ColumnHeader>

                  <TaskList>
                    {columnTasks.length === 0 ? (
                      <EmptyColumn>Nenhuma task</EmptyColumn>
                    ) : (
                      columnTasks.map(task => (
                        <TaskCard
                          key={task.id}
                          $priority={task.priority}
                          $isMatch={task.metadata?.autoGenerated}
                        >
                          {/* Badge de Match Automático */}
                          {task.metadata?.autoGenerated && (
                            <MatchBadge>
                              🎯 Match Score: {task.metadata.matchScore}/100
                            </MatchBadge>
                          )}

                          {/* Título */}
                          <TaskTitle>{task.title}</TaskTitle>

                          {/* Descrição */}
                          {task.description && (
                            <TaskDescription>
                              {task.description.length > 150
                                ? task.description.substring(0, 150) + '...'
                                : task.description}
                            </TaskDescription>
                          )}

                          {/* Footer */}
                          <TaskFooter>
                            <PriorityBadge $priority={task.priority}>
                              {getPriorityLabel(task.priority)}
                            </PriorityBadge>

                            {task.dueDate && (
                              <DueDate>
                                📅{' '}
                                {new Date(task.dueDate).toLocaleDateString(
                                  'pt-BR'
                                )}
                              </DueDate>
                            )}
                          </TaskFooter>

                          {/* Ações */}
                          <TaskActions>
                            {task.metadata?.clientId && (
                              <ActionButton
                                onClick={() =>
                                  navigate(`/clients/${task.metadata.clientId}`)
                                }
                              >
                                👤 Ver Cliente
                              </ActionButton>
                            )}
                            {task.metadata?.propertyId && (
                              <ActionButton
                                onClick={() =>
                                  navigate(
                                    `/properties/${task.metadata.propertyId}`
                                  )
                                }
                              >
                                🏠 Ver Imóvel
                              </ActionButton>
                            )}
                          </TaskActions>
                        </TaskCard>
                      ))
                    )}
                  </TaskList>
                </Column>
              );
            })}
          </KanbanBoard>
        )}
      </KanbanContainer>

      {/* Info Footer */}
      <InfoFooter>
        <InfoText>
          💡 <strong>Dica:</strong> Todas as tasks criadas a partir de matches
          aceitos aparecem aqui automaticamente. Use este workspace para
          organizar seu trabalho pessoal.
        </InfoText>
      </InfoFooter>
    </Container>
  );
}

function getPriorityLabel(priority: string): string {
  const labels: Record<string, string> = {
    low: '🟢 Baixa',
    medium: '🟡 Média',
    high: '🟠 Alta',
    urgent: '🔴 Urgente',
  };
  return labels[priority] || priority;
}

// Styled Components
const Container = styled.div`
  min-height: 100vh;
  background-color: #f9fafb;
`;

const Header = styled.div`
  background: white;
  border-bottom: 1px solid #e5e7eb;
  padding: 2rem;
`;

const HeaderContent = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 1rem;
`;

const TitleSection = styled.div``;

const Title = styled.h1`
  font-size: 2rem;
  font-weight: 700;
  color: #111827;
  margin: 0 0 0.5rem 0;
  display: flex;
  align-items: center;
  gap: 0.75rem;
`;

const PrivateBadge = styled.span`
  background-color: #e9d5ff;
  color: #6b21a8;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
`;

const Subtitle = styled.p`
  font-size: 1rem;
  color: #6b7280;
  margin: 0;
`;

const HeaderActions = styled.div`
  display: flex;
  gap: 0.75rem;
`;

const ViewMatchesButton = styled.button`
  background-color: #3b82f6;
  color: white;
  padding: 0.625rem 1.25rem;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  font-weight: 600;
  border: none;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background-color: #2563eb;
  }
`;

const StatsSection = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1.5rem;
  padding: 2rem;
`;

const StatCard = styled.div<{ $color: string }>`
  background: white;
  border-left: 4px solid ${props => props.$color};
  border-radius: 0.5rem;
  padding: 1.5rem;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
`;

const StatIcon = styled.div`
  font-size: 2rem;
  margin-bottom: 0.5rem;
`;

const StatValue = styled.div`
  font-size: 2rem;
  font-weight: 700;
  color: #111827;
  margin-bottom: 0.25rem;
`;

const StatLabel = styled.div`
  font-size: 0.875rem;
  color: #6b7280;
`;

const KanbanContainer = styled.div`
  padding: 0 2rem 2rem;
`;

const KanbanBoard = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1.5rem;
`;

const Column = styled.div`
  background: #f9fafb;
  border-radius: 0.75rem;
  overflow: hidden;
`;

const ColumnHeader = styled.div<{ $color?: string }>`
  background: ${props => props.$color || '#6b7280'};
  color: white;
  padding: 1rem 1.25rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
`;

const ColumnTitle = styled.h3`
  font-size: 1rem;
  font-weight: 600;
  margin: 0;
`;

const TaskCount = styled.span`
  background: rgba(255, 255, 255, 0.2);
  padding: 0.25rem 0.625rem;
  border-radius: 9999px;
  font-size: 0.75rem;
  font-weight: 600;
`;

const TaskList = styled.div`
  padding: 1rem;
  min-height: 200px;
`;

const EmptyColumn = styled.div`
  text-align: center;
  color: #9ca3af;
  font-size: 0.875rem;
  padding: 2rem 1rem;
`;

const TaskCard = styled.div<{ $priority: string; $isMatch?: boolean }>`
  background: white;
  border-radius: 0.5rem;
  padding: 1rem;
  margin-bottom: 0.75rem;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
  border-left: 3px solid
    ${props => {
      if (props.$isMatch) return '#8B5CF6';
      switch (props.$priority) {
        case 'urgent':
          return '#EF4444';
        case 'high':
          return '#F59E0B';
        case 'medium':
          return '#3B82F6';
        default:
          return '#10B981';
      }
    }};
  transition: all 0.2s;

  &:hover {
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  }
`;

const MatchBadge = styled.div`
  background: linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%);
  color: white;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.375rem 0.625rem;
  border-radius: 0.375rem;
  margin-bottom: 0.75rem;
  display: inline-block;
`;

const TaskTitle = styled.h4`
  font-size: 0.875rem;
  font-weight: 600;
  color: #111827;
  margin: 0 0 0.5rem 0;
  line-height: 1.4;
`;

const TaskDescription = styled.p`
  font-size: 0.75rem;
  color: #6b7280;
  margin: 0 0 0.75rem 0;
  line-height: 1.5;
`;

const TaskFooter = styled.div`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.75rem;
`;

const PriorityBadge = styled.span<{ $priority: string }>`
  font-size: 0.625rem;
  font-weight: 600;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  background-color: #f3f4f6;
  color: #374151;
`;

const DueDate = styled.span`
  font-size: 0.75rem;
  color: #6b7280;
`;

const TaskActions = styled.div`
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
`;

const ActionButton = styled.button`
  background: #f3f4f6;
  color: #374151;
  border: none;
  padding: 0.375rem 0.75rem;
  border-radius: 0.375rem;
  font-size: 0.75rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background: #e5e7eb;
  }
`;

const LoadingContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background-color: #f9fafb;
`;

const LoadingSpinner = styled.div`
  width: 3rem;
  height: 3rem;
  border: 4px solid #e5e7eb;
  border-top-color: #3b82f6;
  border-radius: 50%;
  animation: spin 1s linear infinite;

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
`;

const LoadingText = styled.p`
  margin-top: 1rem;
  color: #6b7280;
  font-size: 0.875rem;
`;

const ErrorContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background-color: #f9fafb;
  text-align: center;
  padding: 2rem;
`;

const ErrorIcon = styled.div`
  font-size: 4rem;
  margin-bottom: 1rem;
`;

const ErrorTitle = styled.h2`
  font-size: 1.5rem;
  font-weight: 700;
  color: #111827;
  margin: 0 0 0.5rem 0;
`;

const ErrorText = styled.p`
  font-size: 1rem;
  color: #6b7280;
  margin: 0;
  max-width: 500px;
`;

const EmptyState = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem 2rem;
  text-align: center;
`;

const EmptyIcon = styled.div`
  font-size: 4rem;
  margin-bottom: 1rem;
`;

const EmptyTitle = styled.h3`
  font-size: 1.25rem;
  font-weight: 700;
  color: #111827;
  margin: 0 0 0.5rem 0;
`;

const EmptyText = styled.p`
  font-size: 1rem;
  color: #6b7280;
  margin: 0;
  max-width: 500px;
`;

const InfoFooter = styled.div`
  background: #eff6ff;
  border-top: 1px solid #dbeafe;
  padding: 1.5rem 2rem;
`;

const InfoText = styled.p`
  font-size: 0.875rem;
  color: #1e40af;
  margin: 0;
  text-align: center;
`;

export default MyWorkspacePage;
